apiVersion: v1
kind: Namespace
metadata:
  name: openobserve
---
# 1. 存储卷声明 (PVC) - 用于持久化数据
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openobserve-data
  namespace: openobserve
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # k3d 默认包含 local-path storage class，这里留空即可自动使用默认值
---
# 2. StatefulSet - 核心应用
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openobserve
  namespace: openobserve
  labels:
    app: openobserve
spec:
  serviceName: openobserve
  replicas: 1
  selector:
    matchLabels:
      app: openobserve
  template:
    metadata:
      labels:
        app: openobserve
    spec:
      containers:
        - name: openobserve
          image: public.ecr.aws/zinclabs/openobserve:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 128m
              memory: 256Mi
            limits:
              cpu: 256m
              memory: 512Gi
          ports:
            - containerPort: 5080
              name: http
          env:
            # --- 初始账号配置 ---
            - name: ZO_ROOT_USER_EMAIL
              value: "ice_moss@163.com"
            - name: ZO_ROOT_USER_PASSWORD
              value: "" # <--- 在这里修改你的默认密码
            # --- 数据目录 ---
            - name: ZO_DATA_DIR
              value: "/srv/openobserver/data"
            # --- 遥测选项 (可选关闭) ---
            - name: ZO_TELEMETRY
              value: "false"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: openobserve-data
---
# 3. Service - 集群内服务发现
apiVersion: v1
kind: Service
metadata:
  name: openobserve
  namespace: openobserve
spec:
  clusterIP: None # Headless service for StatefulSet (optional, but good for DNS)
  selector:
    app: openobserve
  ports:
    - port: 5080
      targetPort: 5080
      name: http
---
# 4. Ingress - 对外暴露 (关键部分)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openobserve-ingress
  namespace: openobserve
  annotations:
    kubernetes.io/ingress.class: "traefik"
    # 如果遇到 HTTPS 重定向问题，可以取消注释下面这行：
    # traefik.ingress.kubernetes.io/router.tls: "false"
spec:
  rules:
    - host: openobserve.iceymoss.com  # <--- 这里的域名
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openobserve
                port:
                  number: 5080